project:
  type: website

website:
  title: "La bruja en la escoba"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/matog/
      - icon: twitter
        href: https://twitter.com/mato
format:
  html:
    theme: cosmo
    css: styles.css



