project:
  type: website
  output-dir: docs
website:
  title: "La bruja en la escoba"
  description: "Un bog de brujas, escobas y cosas"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/matog/
      - icon: twitter
        href: https://twitter.com/mato
format:
  html:
    theme: cosmo
    css: styles.css



